import { Rubik } from "next/font/google";
import AdminNavBar from "@/components/admin-nav-bar";
import "../../globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["arabic", "latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ classes, table }) {
  return (
    <html lang="en">
      <body className={`${rubik.variable} antialiased`} >
        <div dir="rtl" className="w-screen h-screen flex " >
          <nav className="min-w-60 h-screen border-l-[3px] border-[#BFBFBF] bg-white hidden lg:block ">
            <AdminNavBar></AdminNavBar>
          </nav>
          <div className="w-full h-full flex py-24 px-6 gap-6 flex-wrap ">
            <div className="lg:min-w-64 w-full lg:w-fit ">
              {classes}
            </div>
            <div className="flex-grow ">
              {table}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
