import { Rubik } from "next/font/google";
import AdminNavBar from "@/components/admin-nav-bar";
import "../globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["arabic", "latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function AdminDashboardLayout({ children }) {
  return (
    <div dir="rtl" className="w-full h-screen flex justify-start " >
      <nav className="min-w-60 h-full border-l-[3px] border-[#BFBFBF] bg-white hidden lg:block ">
        <AdminNavBar></AdminNavBar>
      </nav>
      <div className="w-full h-full ">
        {children}
      </div>
    </div>
  )
}
